# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/edward/Documents/FPGA_Workspace/fpga_zynq_study/2_projects/fpga_p3_sdk_flash_fixed/fpga_p3_sdk_flash_fixed.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xci
# IP: The module: 'design_1_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/edward/Documents/FPGA_Workspace/fpga_zynq_study/2_projects/fpga_p3_sdk_flash_fixed/fpga_p3_sdk_flash_fixed.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/edward/Documents/FPGA_Workspace/fpga_zynq_study/2_projects/fpga_p3_sdk_flash_fixed/fpga_p3_sdk_flash_fixed.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xci
# IP: The module: 'design_1_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/edward/Documents/FPGA_Workspace/fpga_zynq_study/2_projects/fpga_p3_sdk_flash_fixed/fpga_p3_sdk_flash_fixed.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
